from enum import Enum


class EGameStep(Enum):

    IDLE = 0
    SET_CITY = 1
    SET_BUILDING = 2
    SET_WONDER = 3
    SET_GREAT_PERSON = 4
    SET_STRUCTURE = 5
    SET_PIONEER = 6
    SET_ARMY_NR1 = 7
    SET_ARMY_NR2 = 8
    SET_FIGURE = 9
    CHOOSE_WONDER = 10
    CHOOSE_GREAT_PERSON = 11
    COUNT_TRADING_POINTS = 12
    SWITCH_CIVILIZATION = 13
    MARK_SQUARES_FOR_HIGHLIGHTING_CITY = 14
    GENERAL_SELECT = 15
    SELECT_POLITY = 16
    POLITY_SELECTED = 17
    WONDER_SKILL_SELECTED = 18
    CULTURE_SKILL_SELECTED = 19
    RESEARCH_SKILL_SELECTED = 20
    ARM_MILITARY_UNIT = 21
    DEDICATE_TO_THE_ARTS = 22
    MINING_RESOURCE = 23
    CHOOSE_FIGURE = 24
