from enum import Enum


class EConstants(Enum):
    NUMBER_COINS = 75
    NUMBER_CULTURE = 90
    DELTA_MARKER_BUILDINGS_STACK = 2
    DELTA_MILITARY_UNIT_STACK = 1
    DELTA_CULTURE_CARDS_STACK = 1
    DELTA_WONDER_CARDS_STACK = 1
    DELTA_TOKENS_STACK = 2
    DELTA_RESEARCH_CARDS_STACK = 1
    CULTURE_LEVELS = 22
